### ISSUE TITLE
Fixed stacking order

### ISSUE THREAD

**Issue by mathieudupont** [omarwagih/ggseqlogo#10]
This is a very great tool, beautiful, clean and very flexible, thank you, I love it!
The tutorial is very nice too.
However, it carries a constraint which all LOGO tools I tried also have.
It is not possible to fix the order of stacking.
For example, if my custom alphabet is 'ACGUS', and I would like 'A' to always be on top, then 'C', and so forth down to 'S'.
Instead, the symbol with the greatest value gets put on top, resulting in a lot of undesirable swaping which make it difficult to see motif patterns.
For motif research like I'm doing, it would be very useful to have this option.
Please let me know if you add such an option.
Thanks again!

**Comment by omarwagih** [comment]
I haven't seen much demand for this feature so I probably won't implement it for now, but if you're familiar with R it should be relatively straight forward. It has to do with the `sort` calls in `heights.r`: https://github.com/omarwagih/ggseqlogo/blob/4adc8f298d16f7495dc2bf8abf52bbfebcc9afcc/R/heights.r#L215 

If my memory serves me right, `vals` should be a named numeric vector of heights, where the names are the letters. You would just need to change that order instead of using the sort function.  

The parameter decreasing is passed down from the main `ggseqlogo` function as the `rev_stack_order` parameter: 

https://github.com/omarwagih/ggseqlogo/blob/4adc8f298d16f7495dc2bf8abf52bbfebcc9afcc/R/ggseqlogo.r#L68

Sorry I couldn't be of more help right now!

**Comment by mathieudupont** [comment]
Great, I'll look into this, thanks for the hints!
And thanks for the fast response!
